server:
  port: ${PORT:8761}

eureka:
  instance:
    instanceId: ${DOMAIN_NAME:localhost}
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: ${PORT:8761}
  client:
    registerWithEureka: false
    fetchRegistry: false